name: Backup Firestore

on:
  schedule:
    - cron: "*/1 * * * *"

env:
  PROJECT_ID: rc-dev-demo
  BUCKET: gs://soundsurfer_dev_firestore_backups

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@dev
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET
